[package]
name = "SOAREDS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl33 = { version = "0.2.1" }
glfw = { version = "0.45.0", features = ["all"] }

